package com.RESngos.model;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/app") // This means URL's start with /RESngoAPP (after Application path)
public class MainController {
		@Autowired // This means to get the bean called userRepository
	    // Which is auto-generated by Spring, we will use it to handle the data
	private RestaurantRepository restaurantRepository;
		//localhost:8080/RESngoAPP/add_restaurant?resName=piya&resAddress=pune&resOwner=priyanka&resMobile=4534567867&resEmail=someemail@someemailprovider.com
	@PostMapping(path="/add_restaurant", consumes=MediaType.APPLICATION_JSON_VALUE) // Map ONLY GET Requests
	public @ResponseBody String addNewRestaurant (@RequestBody Restaurant restaurant) {
	// @ResponseBody means the returned String is the response, not a view name
	// @RequestParam means it is a parameter from the GET or POST request
	restaurantRepository.save(restaurant);
	return "Saved";

	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Restaurant> getAllRestaurants() {
	// This returns a JSON or XML with the users
	return restaurantRepository.findAll();
	}


}
